# Generated by Django 5.2 on 2025-04-20 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('FullName', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=254)),
                ('Message', models.CharField()),
            ],
        ),
    ]
