# Generated by Django 5.2 on 2025-04-20 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comments', '0002_contactus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='Email',
            field=models.EmailField(max_length=200),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='Message',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(),
        ),
    ]
