# Generated by Django 5.2 on 2025-04-21 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comments', '0003_alter_contactus_email_alter_contactus_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='Phones',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
