# Generated by Django 5.2 on 2025-04-21 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comments', '0004_contactus_phones'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='Ip',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
