# Generated by Django 5.2 on 2025-04-28 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comments', '0005_contactus_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='Message',
            field=models.TextField(max_length=200),
        ),
    ]
