# Generated by Django 5.2 on 2025-05-08 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comments', '0006_alter_contactus_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'نظر', 'verbose_name_plural': 'نظرات'},
        ),
        migrations.AlterField(
            model_name='contactus',
            name='Email',
            field=models.EmailField(max_length=200, verbose_name='ایمیل کاربر'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='FullName',
            field=models.CharField(max_length=200, verbose_name='نام کامل'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='Ip',
            field=models.CharField(max_length=100, null=True, verbose_name='ایپی کاربر'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='Message',
            field=models.TextField(max_length=200, verbose_name='متن ارسالی'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='Phones',
            field=models.CharField(max_length=50, null=True, verbose_name='شماره تماس'),
        ),
    ]
