# Generated by Django 5.2 on 2025-05-08 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ask',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('caption', models.TextField(max_length=2000)),
                ('Created', models.DateTimeField()),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'سوال',
                'verbose_name_plural': 'سوال ها',
            },
        ),
        migrations.CreateModel(
            name='CommentAsk',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('text', models.TextField(max_length=2000)),
                ('Created', models.DateTimeField()),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publics.ask')),
            ],
            options={
                'verbose_name': 'جواب سوالات',
                'verbose_name_plural': 'جواب ها',
            },
        ),
    ]
