# Generated by Django 5.2 on 2025-05-22 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ask',
            name='Id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
